/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class excute */

#ifndef _Included_excute
#define _Included_excute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     excute
 * Method:    readMsgFromMsgQ
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_excute_readMsgFromMsgQ
  (JNIEnv *, jobject, jint);

/*
 * Class:     excute
 * Method:    writeToShmAndRecall
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_excute_writeToShmAndRecall
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
